name = "kct-menswear"
type = "webpack"
account_id = ""  # Add your Cloudflare account ID
workers_dev = true
route = "kctmenswear.com/*"
zone_id = ""  # Add your Cloudflare zone ID

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
workers_dev = false
route = "kctmenswear.com/*"

[env.staging]
workers_dev = true
name = "kct-menswear-staging"